Ruby on Rails capstone project - Budget app
citec-47/budgetApp pull request #7
Opened 2023-08-07 12:27 UTC by citec-47

### In this PR I did the following

- [ ]  Splash screen

- A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.

- [ ]  Sign up and log in pages
-The user should be able to register in the app with full name, email and password (all mandatory).
- The user can log into the app using email and password.
- If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

- [ ]  Home page (categories page)
![image](https://github.com/citec-47/budgetApp/assets/93107716/927d072e-dc02-4140-b578-b53ebd2a099a)

- When the user logs in, they are presented with the categories page.
- For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.
- When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.
- There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

- [ ] Transactions page
- For a given category, the list of transactions is presented, ordered by the most recent.
- At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).
- There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

- [ ]  "Add a new category" page
- The user fills out a form to create a new category, indicating their name and icon (both mandatory).
- The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.
- When the user clicks on the "Back" button (<), the user navigates to the home page.

- [ ]  "Add a new transaction" page
- The user fills out a form to create a new transaction with:
- name (mandatory)
- amount (mandatory)
- categories (mandatory at least one)
- The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.
- When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

2023-08-08 19:02 UTC, cynthiainga requested changes
Hi @citec-47, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] Users can login and signup ✔️ 
- [ ] The app works as expected ✔️ 
- [ ] No linters errors ✔️ 

## Required Changes ♻️

- [ ] Please kindly record another video after fixing the design and make sure your video has a good sound 😁 😁 
- [ ] Kindly make sure all the tests are passing 🙏🏾 

<img width="1055" alt="Screenshot 2023-08-08 at 22 00 20" src="https://github.com/citec-47/budgetApp/assets/74501523/0c2ffd58-1242-4fcf-bfd3-9a8bf0982f03">

- [ ] Kindly check the comments under the review 👇🏾 👇🏾 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-08 19:02 UTC, cynthiainga commented on app/models/user.rb
>           :recoverable, :rememberable, :validatable
- [ ] Please kindly add `confirmable` to the devise to confirm the email address 🙃 🙃

2023-08-08 19:02 UTC, cynthiainga commented on app/views/devise/registrations/new.html.erb
- [ ] As mentioned in the project requirements you should follow the given design, it's very important to follow the design because in the future if you have a client who gives you a design to reproduce you should pay intention to every detail 🙃 

> |     | your design                       | given design                    |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="329" alt="Screenshot 2023-08-08 at 20 08 40" src="https://github.com/citec-47/budgetApp/assets/74501523/baf01652-4833-4a6c-a3ce-755468bb8210"> | <img width="233" alt="Screenshot 2023-08-08 at 20 08 13" src="https://github.com/citec-47/budgetApp/assets/74501523/d1df7b6a-79f2-4883-99d4-666d09018c3c"> |
> |     | Your signup page                        | The given design                    |     |
> |     | <img width="329" alt="Screenshot 2023-08-08 at 20 10 05" src="https://github.com/citec-47/budgetApp/assets/74501523/f91f11a4-dbdb-431f-b4d3-65ede0dbb851">  |  <img width="283" alt="Screenshot 2023-08-08 at 20 13 34" src="https://github.com/citec-47/budgetApp/assets/74501523/66ab85a3-225d-49d3-b7d8-65b13a0ca694">

2023-08-08 19:02 UTC, cynthiainga commented on app/views/devise/sessions/new.html.erb
- [ ] Please kindly follow the design properly 🙏🏾 🙏🏾 , also kindly make sure you use the same color  🙃 🙃 

> |     | your design                       | given design                    |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="329" alt="Screenshot 2023-08-08 at 20 09 48" src="https://github.com/citec-47/budgetApp/assets/74501523/48a82482-3188-465b-ae6f-e65f822d0b28"> | <img width="283" alt="Screenshot 2023-08-08 at 20 13 19" src="https://github.com/citec-47/budgetApp/assets/74501523/f37a1204-adc1-415f-85b5-ff1ee8e38844">

2023-08-08 19:02 UTC, cynthiainga commented on app/views/home/index.html.erb
- [ ] Please kindly work a little bit on your design 🙃 

> |     | your design                       | given design                    |     |
> | --- | ----------------------------------- | ------------------------------------ | --- |
> |     | <img width="331" alt="Screenshot 2023-08-08 at 20 23 59" src="https://github.com/citec-47/budgetApp/assets/74501523/1cf791d2-19dd-40c8-ac87-5112555a02b9"> | <img width="253" alt="Screenshot 2023-08-08 at 21 52 44" src="https://github.com/citec-47/budgetApp/assets/74501523/cde0498f-8732-4569-ab71-9ddd0d083b90">

2023-08-08 19:02 UTC, cynthiainga commented on app/views/balances/show.html.erb
- [ ] Please kindly make sure you have a button like the one in the design 😁 
All the buttons have this design

The given design

<img width="236" alt="Screenshot 2023-08-08 at 21 56 05" src="https://github.com/citec-47/budgetApp/assets/74501523/1c33bb58-ef96-430b-b29a-2472fb953d51">

Yours

<img width="323" alt="Screenshot 2023-08-08 at 21 56 23" src="https://github.com/citec-47/budgetApp/assets/74501523/39c77853-e890-4207-b122-d96a07591e51">

2023-08-09 15:56 UTC, Gambit142 approved these changes
Hi @citec-47 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

## Highlights
- Setup linters correctly ✔️ 
- The database schema reflects the structure given ✔️ 
- Use of `devise` for authentication✔️ 
- Installed `rspec` gem for writing tests ✔️ 
- Wrote unit and integration tests ✔️ 
- Design layout of the application is identical to that of the Behance design ✔️ 

### Optional Suggestion

#### Great work recording the video again and displaying the changes you carried out in the video. However, I noticed that the audio quality of the video recorded is low. Kindly work on the audio of video recording applications that you have by configuring the speakers correctly or by saving and acquiring a new speaker. 👍 😎 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 23:43 UTC, merged